### ISSUE TITLE
Wrong importing path when installed via Cocoapods

### ISSUE THREAD

**Issue by GorkaMM** [Notificare/notificare-push-lib#2]
Xcode gives this error when the library is installed through Cocoapods:
![screen shot 2015-01-07 at 13 13 38](https://cloud.githubusercontent.com/assets/1714234/5645444/9d7b01f4-966f-11e4-9834-136e9ef9664b.png)

This happens because the pod doesn't preserve the directories in the Xcode project, so it's fixed either by telling the Podspec to preserve directories or by removing the folder (i.e.: "Categories/") from the import statement.

**Comment by jjonthemix** [comment]
Hi Gorka, 

I'm preparing a new release which I plan to make it available tonight. This new release will remove the directory from the import statement. Thanks for the email and keep an eye on this repo. Regards,
