### ISSUE TITLE
-[NSArray subarrayWithRange:]: range {0, 2} extends beyond bounds [0 .. 0]

### ISSUE THREAD

**Issue by GorkaMM** [Notificare/notificare-push-lib#5]
After the 1.4.1 update of the iOS SDK that fixed the `attempt to insert nil object from objects[4]` exception, the library is throwing this new one:
```
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSArray subarrayWithRange:]: range {0, 2} extends beyond bounds [0 .. 0]'
```
This is the stack trace:
```
0   ???                                 0x04398b74 0x0 + 70880116,
1   (appname)                           0x000d5f15 main + 0,
2   libsystem_c.dylib                   0x34776915 <redacted> + 0,
3   libc++abi.dylib                     0x33ab39c9 __cxa_bad_cast + 0,
4   libc++abi.dylib                     0x33acd671 <redacted> + 0,
5   libobjc.A.dylib                     0x34190f25 <redacted> + 192,
6   libc++abi.dylib                     0x33acade3 <redacted> + 78,
7   libc++abi.dylib                     0x33aca5a9 <redacted> + 0,
8   libobjc.A.dylib                     0x34190d5f objc_exception_throw + 250,
9   CoreFoundation                      0x26947a45 <redacted> + 0,
10  (appname)                           0x001dc48f -[NotificarePushLib registerForNotifications] + 1110,
11  (appname)                           0x00104945 -[UPCAppDelegate notificarePushLib:onReady:] + 140,
12  (appname)                           0x001da551 __41-[NotificarePushLib fetchApplicationInfo]_block_invoke + 748,
13  libdispatch.dylib                   0x016f19db _dispatch_call_block_and_release + 10,
14  libdispatch.dylib                   0x016f19c7 _dispatch_client_callout + 22,
15  libdispatch.dylib                   0x016f53ed _dispatch_main_queue_callback_4CF + 808,
16  CoreFoundation                      0x269a03b1 <redacted> + 8,
17  CoreFoundation                      0x2699eab1 <redacted> + 1512,
18  CoreFoundation                      0x268ec3c1 CFRunLoopRunSpecific + 476,
19  CoreFoundation                      0x268ec1d3 CFRunLoopRunInMode + 106,
20  GraphicsServices                    0x2dcea0a9 GSEventRunModal + 136,
21  UIKit                               0x29efbfa1 UIApplicationMain + 1440,
22  (appname)                           0x000d5f89 main + 116,
23  libdyld.dylib                       0x34710aaf <redacted> + 2
```
The way of initializing and using Notificare Push Lib is exactly as in the previously reported bug: https://github.com/Notificare/notificare-push-lib/issues/4

Thank you!

**Comment by GorkaMM** [comment]
I need to add that when this happens once, it will keep crashing the app on every run, so it can't be used at all. It's critical to fix it as soon as possible, please.

**Comment by jjonthemix** [comment]
Hi Gorka, 

This is not related to the release it self, it seems you have a Rich Push template without any actions. Make sure you add at least 2 actions (for the minimal context) to each template or remove it completely from the dashboard. I'm sure if you do this that crash will not happen.

Regards,

**Comment by GorkaMM** [comment]
Why should it have two actions as a requirement? I only have and want one configured in my app.

**Comment by jjonthemix** [comment]
Hi Gorka, 

We will change that in the next release. But right now if you wish to use the actionable notifications you will need to add 2 actions at least. I'll try to release this asap so you can use only one action.

Thanks.

**Comment by GorkaMM** [comment]
I just added an empty action to the Notificare's Rich Push template and it's not crashing now, so it's not that urgent anymore, but please, change this to not requiere any minimum so I can remove that dumb action from the template.

Thank you!

**Comment by jjonthemix** [comment]
Hi Gorka, 

Can I advise to use a destructive button with something like "Ignore" until we release this. I will try to have a release by today or tomorrow. Thanks.
