### ISSUE TITLE
Header file annotation

### ISSUE THREAD

**Issue by bartsoeters** [Notificare/notificare-push-lib#6]
The header files of the Notificare library are not annotated with nullable/nonnull. This causes problems when we use the Notificare library in combination with Swift. Would like to see this fixed so we don't have to annotate these header files ourself.

Some parameters of functions are also not properly documented. These generate warnings after importing them in the project.

**Comment by jjonthemix** [comment]
Hi Bart, 

Can you provide more info, maybe some screenshots with your warnings, because we do not see any warnings when using this lib in a swift project. Thank you.

Regards,

**Comment by bartsoeters** [comment]
Hi,

When receiving the NotificareDeviceInbox objects the property 'data' is nullable. All the header files do not have any annotation therefore it is hard for Swift to know which objects are nullable. 

In the latest version 1.8.2 in the NotifcarePushLib.h line 1241 generates a warning because it does not have a token parameter in the function.

- *  @param token A NSString representing the email address for the account to be recovered
- */
- (void)sendPassword:(NSString *)email completionHandler:(SuccessBlock)result errorHandler:(ErrorBlock)errorBlock;
  /*!

Greetings

**Comment by jjonthemix** [comment]
Hi Bart, 

Although this should not generate a warning unless you're using this method, the header file description for that method will be corrected in the next release, it is indeed incorrect. But the nullable properties of models are not an issue, please assume that all properties of a model are nullable. We've tried to reproduce this and we simply don't get any compiler warnings.

Can you describe a way to reproduce this?

Regards,

**Comment by bartsoeters** [comment]
Hi Joel,

For me it generates a warning, this is default behavior for each incorrect documented parameter. 

Since the header files are not marked with anything Swift expects these properties to be there. I'm aware that I should expect everything to be nullable, this requires some casting every now and than. Correctly marking the header files with nullables would eliminate this.

Regards

**Comment by jjonthemix** [comment]
Hi Bart, 

We've added this properties to Models in version 1.8.4. Can you please updated your pods?

Regards,
