### ISSUE TITLE
'NotificareReactNativeIOS.h' file not found iOS

### ISSUE THREAD

**Issue by marjan89** [Notificare/notificare-push-lib#7]
Hello,

I followed the installation instructions found [here](https://docs.notifica.re/sdk/v1/react-native/ios/implementation/).

**Environment:**
react native version 0.55.4

**Issue:**
Adding `#import "NotificareReactNativeIOS.h"` to AppDelgate.m produces this error `'NotificareReactNativeIOS.h' file not found`.

**What i tried:**
Copying files from [here](https://github.com/Notificare/notificare-push-lib/archive/master.zip) (all except `NotificareTags.plist` as it is missing)

Copying files from v1 branch since it includes the file `NotificareTags.plist` missing from master branch.

Any help appreciated!

**Comment by jjonthemix** [comment]
Hi Marjan89, 

It seems your project can't find the library, this might be a symptom of failing to link the native library. 
 
We are in the process of updating some parts of our document website, I do believe the following step is missing in our docs:

react-native link

This should be done after installing the npm package. Also important that if your react native is running you might need to stop it and start it again by running:

react-native run-ios

We will update the docs asap. Can you please continue with any questions you might have via our support channel located here:

https://notificare.zendesk.com/

Or simply by sending questions via support@notifica.re. Thank you.
