### ISSUE TITLE
 Could not cast value of type 'NotificareAppDelegateSurrogate'  to 'PROJECTNAME.AppDelegate'

### ISSUE THREAD

**Issue by JayMehta711** [Notificare/notificare-push-lib#8]
Hello Team , 
I have received error because of Notificare  SDK in swift 4.2  after updated pods(Notificare pod version 2.0.0)
Error: 
 _Could not cast value of type 'NotificareAppDelegateSurrogate' (0x103b05a78) to 'PROJECTNAME .AppDelegate'_

Below Constant Variable declare in Constant Swift File : 

**let APPDELEGATE = (UIApplication.shared.delegate as! AppDelegate)**

Here i have received crash because in that APPDELEGATE  have received **'NotificareAppdelegateSurrogate'**  but i need my Project AppDelegate. 

Let me know for solution for same  

Swift : 4.2
Xcode : 10.1 (10B61)
Notificare/notificare-push-lib : 2.0.0

**Comment by jjonthemix** [comment]
Hi Jay, 

Please use the support channel (support@notifica.re) for this type of questions. 

Regards,
