### ISSUE TITLE
Issue with disabling 

### ISSUE THREAD

**Issue by vladyslavshtadler** [Notificare/notificare-push-lib#9]
Hi! I have option to disable location offers in app and when I call stopLocationUpdates() in lib all is fine, but when I disabled location permissions in settings, then turn it on, in app Notificare again starts checking location updates and checkLocationUpdates() returns true. How to fully disable it?

**Comment by jjonthemix** [comment]
Hi vladyslavshtadler, 

Can you please forward your questions to support@notifica.re?

Regards,
